name: HealthBar
version: 1.7.0
author: Rocknatalino
main: com.rocknatalino.plugin.Main
website: https://www.spigotmc.org/resources/healthbar-pratical-and-customizable-1-8-1-17.92041/
api-version: 1.13
commands:
  healthbar:
    usage: /<command>
    aliases:
      - hb
      - h
    permission: healthbar.admin